name: ido-test

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      no-docs: ${{ steps.filter.outputs.no-docs }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          no-docs:
            - '!docs/**', '!*.md'
  test:
    needs: changes
    if: ${{ needs.changes.outputs.no-docs == 'true' }}
    name: +lint-docs
    runs-on: "ubuntu-latest"
    env:
      FORCE_COLOR: 1
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: earthly/actions-setup@main
      - name: Execute lint
        run: earthly --ci -P +lint-docs
