name: CI workflow

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    uses: ./.github/workflows/reuseable-find-pr-changes.yaml
    permissions:
      pull-requests: read
    secrets: inherit
  build-earthly:
    needs: changes
    name: build earthly
    uses: ./.github/workflows/reusable-lint.yaml
    with:
      CONTINUE: ${{ needs.changes.outputs.essential-file != 'false' }}
  ensure-run:
    if: ${{ success() }}
    needs: build-earthly
    runs-on: ubuntu-latest
    name: ensure run
    steps:
      - run: echo ensuring run after earthly build
  test:
    needs: ensure-run
    name: docker test
    uses: ./.github/workflows/reusable-lint.yaml
    with:
      CONTINUE: ${{ needs.changes.outputs.essential-file != 'false' }}
