name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  check_run:
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  print1:
    if: ${{ github.event_name == 'check_run' }}
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo hello world ${{ github.event_name }}
  ido:
    name: ido test
    needs: print1
    if: ${{ failure() && (github.event_name == 'pull_request_target' || github.event.pull_request.head.repo.full_name == 'ido123') }}
    uses: ./.github/workflows/reusable_test.yaml
    with:
      VAL1: ${{ github.ref != 'refs/heads/main' }}
      VAL2: ${{ github.ref == 'refs/heads/main' }}
      VAL3: --BRANCH=${{ github.head_ref }}
  changes:
    #1
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/reuseable-find-pr-changes.yaml
    permissions:
      pull-requests: read
    secrets: inherit
  build-earthly:
    needs: changes
    if: ${{ !failure() }}
    name: build earthly
    uses: ./.github/workflows/reusable-lint.yaml
    with:
      SKIP_JOB: ${{ needs.changes.outputs.essential-file == 'false' }}
  test2:
    needs: build-earthly
    #if: ${{ !failure() && (needs.build-earthly.result == 'success' || needs.build-earthly.result == 'skipped') }}
    if: ${{ !failure() }}
    name: docker test
    uses: ./.github/workflows/reusable-lint.yaml
    with:
      SKIP_JOB: ${{ needs.build-earthly.result != 'success' }}
