name: create pr for fork

on:
  pull_request_target:
    types: [ labeled ]
    branches: [ "main" ]

jobs:
  create-pr:
    if: ${{ github.event.label.name == 'approved-for-tests' }}
    runs-on: "ubuntu-latest"
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_ORG: "ido+test"
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: earthly/actions-setup@main
      - name: list secrets
        run: earthly secrets ls
      - name: run earthly 
        run: earthly --ci +open-pr-for-fork --pr_number=${{ github.actor }}
        
