name: reuseable-lint

on:
  workflow_call:
    inputs:
      SKIP_JOB:
        required: true
        type: boolean

jobs:
  lint-this:
    runs-on: "ubuntu-latest"
    steps:
      - name: first step
        if: ${{inputs.SKIP_JOB}}
        run: echo "going to exit job" && return 1
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: earthly/actions-setup@main
      - name: Execute lint
        run: earthly --ci -P +lint-docs
